// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markers.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getMarkerByID = `-- name: GetMarkerByID :one
SELECT id, short_code, creator_id, name, description, strain, quantity, latitude, longitude, image_url, owner_name, owner_contact, created_at, updated_at FROM markers WHERE id = $1
`

// Returns full marker details by ID
func (q *Queries) GetMarkerByID(ctx context.Context, id uuid.UUID) (Marker, error) {
	row := q.db.QueryRowContext(ctx, getMarkerByID, id)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Strain,
		&i.Quantity,
		&i.Latitude,
		&i.Longitude,
		&i.ImageUrl,
		&i.OwnerName,
		&i.OwnerContact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMarkersLightweight = `-- name: ListMarkersLightweight :many
SELECT id, short_code, name, latitude, longitude
FROM markers
ORDER BY created_at DESC
`

type ListMarkersLightweightRow struct {
	ID        uuid.UUID `json:"id"`
	ShortCode string    `json:"short_code"`
	Name      string    `json:"name"`
	Latitude  string    `json:"latitude"`
	Longitude string    `json:"longitude"`
}

// Returns lightweight marker data for map display
func (q *Queries) ListMarkersLightweight(ctx context.Context) ([]ListMarkersLightweightRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarkersLightweight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarkersLightweightRow{}
	for rows.Next() {
		var i ListMarkersLightweightRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
