// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Marker struct {
	ID           uuid.UUID      `json:"id"`
	ShortCode    string         `json:"short_code"`
	CreatorID    uuid.UUID      `json:"creator_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Strain       sql.NullString `json:"strain"`
	Quantity     sql.NullInt32  `json:"quantity"`
	Latitude     string         `json:"latitude"`
	Longitude    string         `json:"longitude"`
	ImageUrl     sql.NullString `json:"image_url"`
	OwnerName    sql.NullString `json:"owner_name"`
	OwnerContact sql.NullString `json:"owner_contact"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	ExpiresAt time.Time      `json:"expires_at"`
	RevokedAt sql.NullTime   `json:"revoked_at"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         string         `json:"name"`
	Role         sql.NullString `json:"role"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
